### ISSUE TITLE
Update projects to RTM

### ISSUE THREAD

**Issue by rcroeder** [RoguePlanetoid/Windows-10-Universal-Windows-Platform-Tutorials#1]
It appears that these samples are using VS 2015 RC. You should update to RTM
![2015-08-30_13-40-20](https://cloud.githubusercontent.com/assets/2488299/9569344/cc5f5a0e-4f1c-11e5-932b-fc6b4e6f8fe9.jpg)

**Comment by RoguePlanetoid** [comment]
Thanks I'll get onto this as soon as I can but should just be a matter of updating the csproj files, apologies for any inconvenience in the meantime

**Comment by RoguePlanetoid** [comment]
This has now been resolved projects should open in RTM tools
